name: Build and Push to GitHub Container Registry on Dev

on:
  workflow_run:
    workflows: ["Run API Tests"]
    branches:
      - main
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log In to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build API Dev Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/medconnectma/reviews-service:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
