name: Run API Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run Tests
      run: |
        chmod +x scripts/test.sh
        ./scripts/test.sh
